### ISSUE TITLE
Add new item not working

### ISSUE THREAD

**Issue by Silinde87** [Silinde87/spring5-gameaffinity#3]

**Comment by Silinde87** [comment]
java.lang.InstantiationException: spring5.silinde87.gameaffinity.backend.domain.Game
	at java.base/java.lang.Class.newInstance(Class.java:598)

and

2020-10-30 11:48:05.745 ERROR 3360 --- [nio-8080-exec-4] c.v.flow.server.DefaultErrorHandler      : 

java.lang.NullPointerException: null
	at org.vaadin.crudui.form.AbstractAutoGeneratedCrudFormFactory.buildBinder(AbstractAutoGeneratedCrudFormFactory.java:279) ~[crudui-4.3.2.jar:4.3.2]

**Comment by Silinde87** [comment]
Project Lombok's @Builder at POJO and Current Vaadin's Crud-UI impl is the problem.

**Comment by Silinde87** [comment]
There is a problem with BeanValidation. If  crud.getCrudFormFactory().setUseBeanValidation(false); at CrudView, it works.
